name: .NET

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore TownSuite.Web.SSV3Adapter.sln
      - name: Build
        run: dotnet build -c Release TownSuite.Web.SSV3Adapter.sln --no-restore
      - name: Test
        run: dotnet test -c Release TownSuite.Web.SSV3Adapter.sln --verbosity normal --collect:"XPlat Code Coverage" --logger:"trx" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.ExcludeByFile='**/TownSuite.Web.Example/**/*.cs'
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure() # run this step even if previous step failed
        with:
          name: unit tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "**/TestResults/**/coverage.cobertura.xml"
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Write Code Coverage to Job Summary
        run: cat **code-coverage-results.md** >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: |
            TownSuite.Web.SSV3Adapter.Interfaces/bin/Release/*.nupkg
            TownSuite.Web.SSV3Adapter.Prometheus/bin/Release/*.nupkg
            TownSuite.Web.SSV3Adapter/bin/Release/*.nupkg
          retention-days: 1
      - name: SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@v1
        with:
          path: ./TownSuite.Web.SSV3Adapter.sln
